# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/

# The URL of your website.
baseurl = "https://sunwenli.github.io/"  # End your URL with a `/` trailing slash. 以“/”结尾的斜杠结束你的URL
title = "Tec Web"
copyright = "&copy; 2018 Wenli Sun"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = "aa"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = true  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
  # Color theme.
  #    Choose from `default`, `ocean`, `forest`, `coffee`, `dark`, or `1950s`.
  color_theme = "default"

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"

  # Your details.
  # name = "Lena Smith"
  # role = "Professor of Artificial Intelligence"
  #
  # # Organizations/Affiliations.
  # #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  # organizations = [ { name = "Stanford University", url = "" } ]

  name = "Wen day"
  role = "Professor of macOS and iOS"
  # organization = "RayJoy (Beijing) technology co. LTD"
  organization_url = "http://www.rayjoy.com/"
  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "714541080@qq.com"
  address = "The 9th floor, block C, zhizhen building, NO.7 zhichun road, haidian district, Beijing"
  office_hours = "Workday 9:30 to 18:30 or email for appointment"
  phone = "188 1057 5394"
  # skype = "echo123"
  # telegram = "dddddd"

  # Enable Keybase in Contact widget by entering your keybase.io username.
  keybase = ""

  # Discussion link (e.g. link to a forum, mailing list, or chat).
  #   Uncomment line below to use.
  #   discussion = { name = "Discuss", url = "https://discourse.gohugo.io" }

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # Enable/disable map in Contact widget.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 0
  map_api_key = ""
  latitude = "37.4275"
  longitude = "-122.1697"
  zoom = 15

  # Date and time format (refer to Go's date format: http://fuckinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Show estimated reading time for posts?
  reading_time = true

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Display next/previous section pager?
  section_pager = false

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["go", "lisp", "ocaml"]
  # highlight_style = "github"

  # Enable native social sharing buttons?
  sharing = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud , fa-weixin
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:714541080@qq.com"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    # link = "//twitter.com/GeorgeCushen"
    link = "//twitter.com/sunwenli1"

  [[params.social]]
    icon = "weixin"
    icon_pack = "fa"
    link = "weixin://contacts/profile/ershao4896"
    # link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/sunwenli"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 3

[[menu.main]]
  name = "Music"
  url = "#music"
  weight = 4

[[menu.main]]
  name = "Tags"
  url = "#tags"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

# # Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
# [languages.en]
#   languageCode = "en-us"

[[languages.zh.menu.main]]
  name = "主页"
  url = "#about"
  weight = 1

[[languages.zh.menu.main]]
  name = "文章"
  url = "#posts"
  weight = 2

[[languages.zh.menu.main]]
  name = "项目"
  url = "#projects"
  weight = 3

[[languages.zh.menu.main]]
  name = "音乐盒"
  url = "#music"
  weight = 4

[[languages.zh.menu.main]]
  name = "标签"
  url = "#tags"
  weight = 5

[[languages.zh.menu.main]]
  name = "联系"
  url = "#contact"
  weight = 6

  # [[languages.zh.menu.main]]
  #   name = "English"
  #   url = "../"
  #   weight = 7

[languages.en]
  languageCode = "en-us"
  title = "Just Do it"
  organization = "RayJoy (Beijing) technology co. LTD"
  name = "Wenli Sun"
  role = "iOS & macOS Developer"
  address = "The 9th floor, block C, zhizhen building, NO.7 zhichun road, haidian district, Beijing"
  office_hours = "Workday 9:30 to 18:30 or email for appointment"
  # address = "Beijing China"
  # office_hours = "Please send an email for appointment"

[languages.zh]
  languageCode = "zh"
  organization = "雷尚科技 (北京)"
  copyright = "&copy; 2018 孙文礼"
  title = "人未尽,杯莫停"
  name = "孙文礼"
  role = "iOS & macOS 开发者"
  address = "北京市海淀区知春路7号,致真大厦C座9层"
  office_hours = "工作日9:30至18:30或邮件预约会面"
